### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: deskshare.webm

### ISSUE THREAD

**Issue by faridcher** [C0D3D3V/bbb-dl#17]
Hi,

```sh
~ $ bbb-dl "https://class10.ui.ac.ir/playback/presentation/2.3/3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828"
wnloading meta informations
[BBB] 3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828: Downloading webpage
[BBB] 3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828: Downloading XML
[BBB] 3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828: Downloading XML
[BBB] 3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828: Downloading XML
[BBB] Downloading slides
[BBB] Slide slide-000.png is already present
[BBB] Downloading slide deskshare.webm...
WARNING: [BBB] (Try 1 of 3) Unable to download slide "https://class10.ui.ac.ir/presentation/3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828/deskshare/deskshare.webm": HTTP Error 404: Not Found
[BBB] Slide slide-000.png is already present
[BBB] Downloading slide deskshare.webm...
WARNING: [BBB] (Try 1 of 3) Unable to download slide "https://class10.ui.ac.ir/presentation/3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828/deskshare/deskshare.webm": HTTP Error 404: Not Found
[BBB] Slide slide-000.png is already present
[BBB] Downloading slide deskshare.webm...
WARNING: [BBB] (Try 1 of 3) Unable to download slide "https://class10.ui.ac.ir/presentation/3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828/deskshare/deskshare.webm": HTTP Error 404: Not Found
[BBB] Slide slide-000.png is already present
[BBB] Downloading slide deskshare.webm...
WARNING: [BBB] (Try 1 of 3) Unable to download slide "https://class10.ui.ac.ir/presentation/3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828/deskshare/deskshare.webm": HTTP Error 404: Not Found
[BBB] Slide slide-000.png is already present
[BBB] Downloading webcams.webm
ERROR: unable to download video data: HTTP Error 404: Not Found
[BBB] Downloading webcams.mp4
[download] Resuming download at byte 1708937
[download] Destination: 3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828/webcams.mp4
[download] 100% of 27.58MiB in 02:18
[BBB] Downloading deskshare.webm
ERROR: unable to download video data: HTTP Error 404: Not Found
[BBB] Downloading deskshare.mp4
[download] Destination: 3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828/deskshare.mp4
[download] 100% of 14.49MiB in 01:29
[BBB] Create slideshow
[BBB] Trimming slide (frame 0 / 8) at time stamp 00:00 (Duration: 01:30)
frame= 2174 fps=138 q=-1.0 Lsize=    2004kB time=00:01:30.54 bitrate= 181.3kbits/s speed=5.75x
[BBB] Trimming deskshare (frame 1 / 8) at time stamp 01:30 (Duration: 07:38)
Traceback (most recent call last):
File "/home/farid/.local/bin/bbb-dl", line 8, in <module>
sys.exit(main())
File "/home/farid/.local/lib/python3.9/site-packages/bbb_dl/main.py", line 792, in main
BBBDL(args.verbose, args.no_check_certificate, args.encoder, args.filename, args.audiocodec).run(
File "/home/farid/.local/lib/python3.9/site-packages/bbb_dl/main.py", line 282, in run
slideshow_path = self._create_slideshow(slides_infos, video_id, slideshow_w, slideshow_h)
File "/home/farid/.local/lib/python3.9/site-packages/bbb_dl/main.py", line 665, in _create_slideshow
self.ffmpeg.trim_video_by_seconds(
File "/home/farid/.local/lib/python3.9/site-packages/bbb_dl/ffmpeg.py", line 155, in trim_video_by_seconds
self.pp.run_ffmpeg(
File "/home/farid/.local/lib/python3.9/site-packages/bbb_dl/ffmpeg.py", line 66, in run_ffmpeg
self.run_ffmpeg_multiple_files([path], out_path, opts, opts_before)
File "/home/farid/.local/lib/python3.9/site-packages/bbb_dl/ffmpeg.py", line 25, in run_ffmpeg_multiple_files
oldest_mtime = min(os.stat(encodeFilename(path)).st_mtime for path in input_paths)
File "/home/farid/.local/lib/python3.9/site-packages/bbb_dl/ffmpeg.py", line 25, in <genexpr>
oldest_mtime = min(os.stat(encodeFilename(path)).st_mtime for path in input_paths)
FileNotFoundError: [Errno 2] No such file or directory: '3639b36e3d1fc5b25a55ac517be882f2ee026c90-1645590297828/deskshare.webm'
```

I renamed `deskshare.mp4` to `deskshare.webm` and reran `bbb-dl` and it succeeded.

**Comment by C0D3D3V** [comment]
thank you very much :) This should be fixed in version 0.8.0.
