### ISSUE TITLE
Output video does not contain Whiteboard actions

### ISSUE THREAD

**Issue by Qbreak** [C0D3D3V/bbb-dl#24]
Cursor movements and drawings on the screen are not included in the video content. How do I get it to record? -Google translate

**Comment by C0D3D3V** [comment]
Try to use the option `--add-annotations` like: `bbb-dl --add-annotations URL` 
For the cursor/pointer, the code is still in the project, but I removed the option to activate it, because it uses way to much computational power. If you would use it, you would not get happy with it. Maybe someone will someday optimize it a lot, but for now it is not good, because we have to render every frame new, only to add a little cursor, that takes much longer then only to add annotations.

**Comment by Qbreak** [comment]
I'm glad you're so involved. It fulfilled a serious need for me. When I tried to use the feature you mentioned as -aa, it didn't work. It's working now. I'll look into it when it's done. It doesn't matter if it takes hours, if it won't take days, how can I turn this feature on? -translate

**Comment by Qbreak** [comment]
yes i got an error   :(


```
[BBB] Paint image slide-017.png with annotation 116/119 (Frame: 31/31)
[BBB] Paint image slide-017.png with annotation 118/119 (Frame: 31/31)
[BBB] Paint image slide-017.png with annotation 119/119 (Frame: 31/31)
[BBB] Rescale slide-000.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-001.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-002.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-003.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-004.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-005.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-006.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-007.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-008.png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
[BBB] Rescale slide-008_f09_p00.png

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Scripts\bbb-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbb_dl\main.py", line 839, in main
    BBBDL(args.verbose, args.no_check_certificate, args.encoder, args.audiocodec).run(
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbb_dl\main.py", line 311, in run
    slideshow_w, slideshow_h = self._rescale_slides(slides_infos)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbb_dl\main.py", line 682, in _rescale_slides
    self.ffmpeg.rescale_image(slide.path, rescaled_path, new_width, new_height)
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbb_dl\ffmpeg.py", line 90, in rescale_image
    self.pp.own_run_ffmpeg(image, out_file, ["-vf", f"pad={width}:{height}:ow/2-iw/2:oh/2-ih/2"])
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbb_dl\ffmpeg.py", line 79, in own_run_ffmpeg
    self.own_run_ffmpeg_multiple_files([path], out_path, opts, opts_before)
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbb_dl\ffmpeg.py", line 25, in own_run_ffmpeg_multiple_files
    return self.own_real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bluezone\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbb_dl\ffmpeg.py", line 73, in own_real_run_ffmpeg
    raise FFmpegPostProcessorError(msg)
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:_scaled: Invalid argument
```

**Comment by C0D3D3V** [comment]
Can you send me the URL of your bbb session? So that I can debug the code... 

If it is not for public you can send it e.g. via mail (on my profile page).

**Comment by Qbreak** [comment]
I sent an e-mail

**Comment by C0D3D3V** [comment]
If you still get this error, then run the same command but add the `--verbose` option, then open a new issue and send the error log including some previous lines. Or just send it by mail...

**Comment by C0D3D3V** [comment]
Also maybe update ffmpeg xD Not sure what version you have installed, since you did not post the verbose log.

**Comment by C0D3D3V** [comment]
Just in case if you try to download the session again, please make sure the downloaded files are not broken (or just remove them first and then try to run bbb-dl again).
