### ISSUE TITLE
FFmpegPostProcessorError: ffmpeg crashes when facing weird filenames

### ISSUE THREAD

**Issue by rscircus** [C0D3D3V/bbb-dl#3]
Maybe I'm off somewhere, but I get this weird error:

```
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/bbb-dl-vRrSF9wO-py3.7/bin/bbb-dl", line 33, in <module>
    sys.exit(load_entry_point('bbb-dl==0.5', 'console_scripts', 'bbb-dl')())
  File "/home/user/.cache/pypoetry/virtualenvs/bbb-dl-vRrSF9wO-py3.7/lib/python3.7/site-packages/bbb_dl/main.py", line 690, in main
    args.keep_tmp_files,
  File "/home/user/.cache/pypoetry/virtualenvs/bbb-dl-vRrSF9wO-py3.7/lib/python3.7/site-packages/bbb_dl/main.py", line 220, in run
    self.ffmpeg.mux_slideshow_with_webcam(slideshow_path, webcams_path, webcam_w, webcam_h, result_path)
  File "/home/user/.cache/pypoetry/virtualenvs/bbb-dl-vRrSF9wO-py3.7/lib/python3.7/site-packages/bbb_dl/ffmpeg.py", line 88, in mux_slideshow_with_webcam
    "ultrafast",
  File "/home/user/.cache/pypoetry/virtualenvs/bbb-dl-vRrSF9wO-py3.7/lib/python3.7/site-packages/bbb_dl/ffmpeg.py", line 58, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:2021-02-12T11-33-02_TEST 2020/21.mp4: No such file or directory
```

You got any idea why that is? Can it be, that he interprets the "/" as a directory in the filename?

**Comment by rscircus** [comment]
Yes, this is the problem, ffmpeg is crashing here. I rewrote this line. I'll send an MR in a sec.

**Comment by rscircus** [comment]
Alright. That fixed it for me. :blush: ... and now, let's get some :coffee:

**Comment by C0D3D3V** [comment]
Thanks a lot :)
pathvalidate seems to be a good choice. We could have also used the function of youtube-dl. But I think so it is also very good.
