### ISSUE TITLE
Current release 1.0.0 seems to be broken

### ISSUE THREAD

**Issue by snorreflorre** [C0D3D3V/bbb-dl#38]
Hi,

I can't get the current release of bbb-dl to run.

On Windows:
```posh
PS C:\WINDOWS\system32> bbb-dl --help
Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "C:\Users\mail\AppData\Roaming\Python\Python311\Scripts\bbb-dl.exe\__main__.py", line 4, in <module>
    File "C:\Users\mail\AppData\Roaming\Python\Python311\site-packages\bbb_dl\main.py", line 32, in <module>
        from bbb_dl.ffmpeg import FFMPEG
    File "C:\Users\mail\AppData\Roaming\Python\Python311\site-packages\bbb_dl\ffmpeg.py", line 11, in <module>
        from ffmpeg.utils import Progress
ImportError: cannot import name 'Progress' from 'ffmpeg.utils' (C:\Users\mail\AppData\Roaming\Python\Python311\site-packages\ffmpeg\utils.py)
```
WSL-Ubuntu-2204 throws the same error:
```shell
$ bbb-dl --help
Traceback (most recent call last):
File "/home/snorreflorre/.local/bin/bbb-dl", line 5, in <module>
	from bbb_dl.main import main
File "/home/snorreflorre/.local/lib/python3.10/site-packages/bbb_dl/main.py", line 32, in <module>
	from bbb_dl.ffmpeg import FFMPEG
File "/home/snorreflorre/.local/lib/python3.10/site-packages/bbb_dl/ffmpeg.py", line 11, in <module>
	from ffmpeg.utils import Progress
ImportError: cannot import name 'Progress' from 'ffmpeg.utils' (/home/snorreflorre/.local/lib/python3.10/site-packages/ffmpeg/utils.py)
```

**Comment by C0D3D3V** [comment]
I guess it is because the ffmpeg python package got updated (and that also on my request 😂) I have to adapt to the new interface... I will take a look on it now

**Comment by C0D3D3V** [comment]
I think I fixed the problem. Please test the new release. Please report all new issues you face
