### ISSUE TITLE
Fmpeg Non-zero exit status

### ISSUE THREAD

**Issue by redfave** [C0D3D3V/bbb-dl#39]
Hello there,

thank you for sharing your programm.
I encountered an error while downloading specific Videos from BBB. This error occurs reproducible to a subset of videos from a lecture series.

```
PS C:\Users\fooUser> bbb-dl -f DisSimMas_SS2022_... https://....
Output directory for the final video is: C:\Users\fooUser
Directory for the temporary files is: C:\Users\fooUser\AppData\Local\bbb-dl\281cb87d5e05162b6dba3672b7507976
Downloading meta information
metadata.xml is already present
shapes.svg is already present
Downloading webcams / deskshare
cursor.xml is already present
panzooms.xml is already present
captions.json is already present
deskshare.xml is already present
Downloading events.xml...
presentation_text.json is already present
slides_new.xml is already present
Downloading notes.html...
Downloading polls.json...
Downloading external_videos.json...
video/webcams.webm is already present
Downloading video/webcams.mp4...
Downloading deskshare/deskshare.webm...
Downloading deskshare/deskshare.mp4...
notes.html could not be downloaded: 404 Not Found
video/webcams.mp4 could not be downloaded: 404 Not Found
events.xml could not be downloaded: 404 Not Found
external_videos.json could not be downloaded: 404 Not Found
polls.json could not be downloaded: 404 Not Found
deskshare/deskshare.webm could not be downloaded: 404 Not Found
deskshare/deskshare.mp4 could not be downloaded: 404 Not Found
Downloading slides
presentation/e537a2074b7e59c4ab45016011204e518249f90d-1657810862982/slide-1.png is already present
presentation/8614337cf2b16e3c93843d8b44031769f3ead9f4-1657810523966/slide-1.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-1.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-2.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-3.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-4.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-5.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-6.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-7.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-8.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-9.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-10.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-11.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-12.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-13.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-14.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-15.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-16.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-17.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-18.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-19.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-20.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-21.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-22.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-23.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-24.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-25.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-26.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-27.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-28.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-29.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-30.png is already present
presentation/1e7a58a106274a61647104478274a4c46f240dba-1657810578592/slide-31.png is already present
Recording title: DisSimMas_SS2022
Recording date: 2022-07-14T16-53-33
Recording duration: 30:36
No desk was shared in this session
Start capturing frames...
Output directory for frames is: C:\Users\fooUser\AppData\Local\bbb-dl\281cb87d5e05162b6dba3672b7507976\frames
Initialization takes a few seconds...

Done: 00000 / 04509 Frames | 000 / 001 Parts \
Partition already finished: 0 to 1:02:23

Frames capturing is finished and took: 37.
Start creating slideshow...
Slideshow does already exist! Skipping rendering!
Try to detect freeze in video/webcams.webm...
Frame: 27540 FPS: 763.0 Size: 0 Time: 30:35 Bitrate: 0.0 Speed: 50.8x -
Command finished
Detection of freeze finished and took: 37
Webcam is empty, webcam will not be added to the final presentation
Mux final slideshow
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fooUser\AppData\Roaming\Python\Python311\Scripts\bbb-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\fooUser\AppData\Roaming\Python\Python311\site-packages\bbb_dl\main.py", line 1465, in main
    bbb_dl.run()
  File "C:\Users\fooUser\AppData\Roaming\Python\Python311\site-packages\bbb_dl\main.py", line 265, in run
    result_path = self.final_mux(slideshow_path, webcams_path, webcams_rel_path, metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fooUser\AppData\Roaming\Python\Python311\site-packages\bbb_dl\main.py", line 1115, in final_mux
    asyncio.run(
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\fooUser\AppData\Roaming\Python\Python311\site-packages\bbb_dl\ffmpeg.py", line 313, in add_audio_to_slideshow
    await ffmpeg.execute()
  File "C:\Users\fooUser\AppData\Roaming\Python\Python311\site-packages\ffmpeg\asyncio\ffmpeg.py", line 141, in execute
    raise FFmpegError(f"Non-zero exit status {self._process.returncode}")
ffmpeg.ffmpeg.FFmpegError: Non-zero exit status 1
```

Windows 11 x64
Python 3.11.0
ffmpeg version 6.0-full_build-www.gyan.dev (Installed with winget)

**Comment by C0D3D3V** [comment]
Please provide the verbose log. Use the -v option
And if possible send me the lecture URL (via mail?)
I guess it is related with the fact that the created slideshow is 1:02:23 long while the webcam video only 30:35

**Comment by redfave** [comment]
Thank you for the fast reply. I've sent you a full log with details to your mail :)

**Comment by C0D3D3V** [comment]
fix is released
