### ISSUE TITLE
Download fail - bbb.hu-berlin.de

### ISSUE THREAD

**Issue by ds2k5** [C0D3D3V/bbb-dl#62]
URL: https://bbb.hu-berlin.de/playback/presentation/2.3/5bcd92c514eb9deda1b08f163fcd7cc692dfd5c6-1720111194731

Command:   **bbb-dl https://bbb.hu-berlin.de/playback/presentation/2.3/5bcd92c514eb9deda1b08f163fcd7cc692dfd5c6-1720111194731**

```
Output directory for frames is: /home/username/.local/share/bbb-dl/77be49f30eb1ec1942fb3d82bc5e2abb/frames
Initialization takes a few seconds...

Done: 00000 / 00741 Frames | 000 / 047 Parts /Traceback (most recent call last):
  File "/home/developer/Downloads/bbb-dl-1.0.13/bbb_dl/main.py", line 439, in _real_multi_capture_frames
    await gather_jobs
  File "/home/developer/Downloads/bbb-dl-1.0.13/bbb_dl/main.py", line 508, in capture_frames
    browser = await p.chromium.launch()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.local/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 14398, in launch
    await self._impl_obj.launch(
  File "/home/developer/.local/lib/python3.11/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/developer/.cache/ms-playwright/chromium-1140/chrome-linux/chrome
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
Unexpected Error! Press Ctr+C to exit. Please try to set a low number of threads with `--max-parallel-chromes`. You can contact bbb-dl support.

```

Using: Debian 12 x86_64
Browser: chromium Version 130.0.6723.69-1

bbb-dl-1.0.13

How to fix this ?

```

$ bbb-dl --max-parallel-chromes https://bbb.hu-berlin.de/playback/presentation/2.3/5bcd92c514eb9deda1b08f163fcd7cc692dfd5c6-1720111194731
usage: bbb-dl [-h] [-ao] [-sw] [-swfd] [-sa] [-sc] [-sz] [-bk] [-kt] [-v] [--ffmpeg-location FFMPEG_LOCATION] [-scv] [-ais] [-uac] [-ftv FORCE_TLS_VERSION] [--version] [--encoder ENCODER]
              [--audiocodec AUDIOCODEC] [--preset PRESET] [--crf CRF] [-f FILENAME] [-od OUTPUT_DIR] [-wd WORKING_DIR] [-mpc MAX_PARALLEL_CHROMES] [-fw FORCE_WIDTH] [-fh FORCE_HEIGHT]
              URL
bbb-dl: error: argument -mpc/--max-parallel-chromes: invalid int value: 'https://bbb.hu-berlin.de/playback/presentation/2.3/5bcd92c514eb9deda1b08f163fcd7cc692dfd5c6-1720111194731'

```

**Comment by C0D3D3V** [comment]
Run `playwright install` in your terminal. 
And send the output of it here. 

Then try to run bbb-dl again

**Comment by ds2k5** [comment]
@C0D3D3V 

```
$ playwright install
bash: playwright: command not found

```

```
$ pip install --user playwright
Requirement already satisfied: playwright in /home/developer/.local/lib/python3.11/site-packages (1.48.0)
Requirement already satisfied: greenlet==3.1.1 in /home/developer/.local/lib/python3.11/site-packages (from playwright) (3.1.1)
Requirement already satisfied: pyee==12.0.0 in /home/developer/.local/lib/python3.11/site-packages (from playwright) (12.0.0)
Requirement already satisfied: typing-extensions in /usr/lib/python3/dist-packages (from pyee==12.0.0->playwright) (4.4.0)

```

Install command was:  pip install --user bbb-dl

**Comment by C0D3D3V** [comment]
I guess you have not added python to your PATH (during installation, there was a checkbox to add it to your PATH). To be percise your python user scripts are not in PATH. (since you installed with --user, not the global scripts directory is used).
 
try to run `python -m playwright install` that should skip the PATH problem.

Btw. :D interesting talk ^^ I think I will watch it.

**Comment by ds2k5** [comment]
>try to run python -m playwright install that should skip the PATH problem.

Thank you that solved the issue !
Download is runing now!

have a nice day!

>Btw. :D interesting talk ^^ I think I will watch it.

cool have fun
